// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nailify.Capstone.Infrastructure.DBContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nailify.Capstone.Infrastructure.Migrations
{
    [DbContext(typeof(NailifyDbContext))]
    [Migration("20260603081735_TuePDG-RemoveSkillInVariant")]
    partial class TuePDGRemoveSkillInVariant
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryTypeId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryTypeId");

                    b.ToTable("CategoryTypes");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtist", b =>
                {
                    b.Property<Guid>("NailArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NailArtistId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("SalonId");

                    b.ToTable("NailArtists");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailCategory", b =>
                {
                    b.Property<int>("NailCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("NailDesignId")
                        .HasColumnType("integer");

                    b.HasKey("NailCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NailDesignId", "CategoryId")
                        .IsUnique();

                    b.ToTable("NailCategories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailComponent", b =>
                {
                    b.Property<int>("NailComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailComponentId"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FingerIndex")
                        .HasColumnType("integer")
                        .HasComment("-1 = whole hand, 0-9 = specific finger index");

                    b.Property<int>("NailVariantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PosX")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PosY")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("NailComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("NailVariantId");

                    b.ToTable("NailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesign", b =>
                {
                    b.Property<int>("NailDesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailDesignId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NailDesignId");

                    b.ToTable("NailDesigns");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesignImage", b =>
                {
                    b.Property<int>("NailDesignImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailDesignImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NailDesignId")
                        .HasColumnType("integer");

                    b.HasKey("NailDesignImageId");

                    b.HasIndex("NailDesignId");

                    b.ToTable("NailDesignImages");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailShape", b =>
                {
                    b.Property<int>("NailShapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailShapeId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("NailShapeId");

                    b.ToTable("NailShapes");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailSurface", b =>
                {
                    b.Property<int>("NailSurfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailSurfaceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShaderParam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NailSurfaceId");

                    b.ToTable("NailSurfaces");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailVariant", b =>
                {
                    b.Property<int>("NailVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailVariantId"));

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NailDesignId")
                        .HasColumnType("integer");

                    b.Property<int>("NailShapeId")
                        .HasColumnType("integer");

                    b.Property<int>("NailSurfaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("NailVariantId");

                    b.HasIndex("NailDesignId");

                    b.HasIndex("NailShapeId");

                    b.HasIndex("NailSurfaceId");

                    b.ToTable("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Salon", b =>
                {
                    b.Property<Guid>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SalonId");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.SalonOperatingHour", b =>
                {
                    b.Property<Guid>("OperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("uuid");

                    b.HasKey("OperatingHourId");

                    b.HasIndex("SalonId");

                    b.ToTable("SalonOperatingHours");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NailArtistId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ShiftEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ShiftStart")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleId");

                    b.HasIndex("NailArtistId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Category", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtist", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "Account")
                        .WithOne()
                        .HasForeignKey("Nailify.Capstone.Domain.Entities.NailArtist", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.Salon", "Salon")
                        .WithMany("NailArtists")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailCategory", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Category", "Category")
                        .WithMany("NailCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany("NailCategories")
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("NailDesign");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailComponent", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Component", "Component")
                        .WithMany("NailComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailVariant", "NailVariant")
                        .WithMany("NailComponents")
                        .HasForeignKey("NailVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("NailVariant");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesignImage", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany("NailDesignImages")
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NailDesign");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailVariant", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany("NailVariants")
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailShape", "NailShape")
                        .WithMany("NailVariants")
                        .HasForeignKey("NailShapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailSurface", "NailSurface")
                        .WithMany("NailVariants")
                        .HasForeignKey("NailSurfaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NailDesign");

                    b.Navigation("NailShape");

                    b.Navigation("NailSurface");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.SalonOperatingHour", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Salon", "Salon")
                        .WithMany("OperatingHours")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailArtist", "NailArtist")
                        .WithMany("Schedules")
                        .HasForeignKey("NailArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NailArtist");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Category", b =>
                {
                    b.Navigation("NailCategories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Component", b =>
                {
                    b.Navigation("NailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtist", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesign", b =>
                {
                    b.Navigation("NailCategories");

                    b.Navigation("NailDesignImages");

                    b.Navigation("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailShape", b =>
                {
                    b.Navigation("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailSurface", b =>
                {
                    b.Navigation("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailVariant", b =>
                {
                    b.Navigation("NailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Salon", b =>
                {
                    b.Navigation("NailArtists");

                    b.Navigation("OperatingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
