// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nailify.Capstone.Infrastructure.DBContext;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nailify.Capstone.Infrastructure.Migrations
{
    [DbContext(typeof(NailifyDbContext))]
    [Migration("20260623122326_TuePDG-AddDiscountInBooking")]
    partial class TuePDGAddDiscountInBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CheckInImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("CheckOutImagesUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("NailArtistId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("QRCode")
                        .HasColumnType("text");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalDuration")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("NailArtistId");

                    b.HasIndex("SalonId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingHistory", b =>
                {
                    b.Property<Guid>("BookingHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.HasKey("BookingHistoryId");

                    b.HasIndex("ActorId");

                    b.HasIndex("BookingId");

                    b.ToTable("BookingHistories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingItem", b =>
                {
                    b.Property<Guid>("BookingItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CustomerNailId")
                        .HasColumnType("integer");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int?>("NailVariantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("BookingItemId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerNailId");

                    b.HasIndex("NailVariantId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingItems");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingProcedure", b =>
                {
                    b.Property<Guid>("BookingProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CompletedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ProcedureId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcedureName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("BookingProcedureId");

                    b.HasIndex("BookingItemId");

                    b.HasIndex("CompletedById");

                    b.HasIndex("ProcedureId");

                    b.ToTable("BookingProcedures");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryTypeId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CategoryType", b =>
                {
                    b.Property<int>("CategoryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("CategoryTypeId");

                    b.ToTable("CategoryTypes");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponentId"));

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("LifetimePoints")
                        .HasColumnType("integer");

                    b.Property<int>("LoyaltyPoint")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("LoyaltyTierId")
                        .HasColumnType("integer");

                    b.Property<string>("NailCondition")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Occupation")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasDefaultValue("");

                    b.Property<string>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("SkinTone")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.HasKey("UserId");

                    b.HasIndex("LoyaltyTierId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerComponent", b =>
                {
                    b.Property<int>("CustomerComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerComponentId"));

                    b.Property<int>("ComponentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerComponentId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerNail", b =>
                {
                    b.Property<int>("CustomerNailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerNailId"));

                    b.Property<Guid?>("ApprovedArtistId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomColor")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("NailShapeId")
                        .HasColumnType("integer");

                    b.Property<int?>("NailSurfaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<Guid?>("SalonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CustomerNailId");

                    b.HasIndex("ApprovedArtistId");

                    b.HasIndex("NailShapeId");

                    b.HasIndex("NailSurfaceId");

                    b.HasIndex("SalonId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerNails");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerNailComponent", b =>
                {
                    b.Property<int>("CustomerNailComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CustomerNailComponentId"));

                    b.Property<int?>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CustomerComponentId")
                        .HasColumnType("integer");

                    b.Property<int>("CustomerNailId")
                        .HasColumnType("integer");

                    b.Property<int>("FingerIndex")
                        .HasColumnType("integer")
                        .HasComment("-1 = whole hand, 0-9 = specific finger index");

                    b.Property<decimal>("PosX")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PosY")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CustomerNailComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("CustomerComponentId");

                    b.HasIndex("CustomerNailId");

                    b.ToTable("CustomerNailComponents", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerNailComponent_OneComponent", "(\"ComponentId\" IS NOT NULL AND \"CustomerComponentId\" IS NULL) OR (\"ComponentId\" IS NULL AND \"CustomerComponentId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.FavoriteNail", b =>
                {
                    b.Property<int>("FavoriteNailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteNailId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NailDesignId")
                        .HasColumnType("integer");

                    b.Property<int?>("NailVariantId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FavoriteNailId");

                    b.HasIndex("NailDesignId");

                    b.HasIndex("NailVariantId");

                    b.HasIndex("UserId", "NailDesignId", "NailVariantId")
                        .IsUnique();

                    b.ToTable("FavoriteNails", t =>
                        {
                            t.HasCheckConstraint("CK_FavoriteNail_DesignOrVariant", "\"NailDesignId\" IS NOT NULL OR \"NailVariantId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.LoyaltyTier", b =>
                {
                    b.Property<int>("LoyaltyTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoyaltyTierId"));

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text");

                    b.Property<string>("ColorJson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("numeric");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("MaxLifetimePoints")
                        .HasColumnType("integer");

                    b.Property<int?>("MinLifetimePoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<string>("TextColor")
                        .HasColumnType("text");

                    b.HasKey("LoyaltyTierId");

                    b.HasIndex("MinLifetimePoints")
                        .IsUnique();

                    b.ToTable("LoyaltyTiers");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.LoyaltyTransaction", b =>
                {
                    b.Property<int>("LoyaltyTransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoyaltyTransactionId"));

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("LoyaltyTierIdAtTime")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Earned");

                    b.HasKey("LoyaltyTransactionId");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("LoyaltyTierIdAtTime");

                    b.ToTable("LoyaltyTransactions");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtist", b =>
                {
                    b.Property<Guid>("NailArtistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("NailArtistId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("NailArtists");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtistSkill", b =>
                {
                    b.Property<Guid>("NailArtistSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("NailArtistId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("NailArtistSkillId");

                    b.HasIndex("SkillTypeId");

                    b.HasIndex("NailArtistId", "SkillTypeId")
                        .IsUnique();

                    b.ToTable("NailArtistSkills");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailCategory", b =>
                {
                    b.Property<int>("NailCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("NailDesignId")
                        .HasColumnType("integer");

                    b.HasKey("NailCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NailDesignId", "CategoryId")
                        .IsUnique();

                    b.ToTable("NailCategories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailComponent", b =>
                {
                    b.Property<int>("NailComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailComponentId"));

                    b.Property<int>("ComponentId")
                        .HasColumnType("integer");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FingerIndex")
                        .HasColumnType("integer")
                        .HasComment("-1 = whole hand, 0-9 = specific finger index");

                    b.Property<int>("NailVariantId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PosX")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PosY")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("NailComponentId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("NailVariantId");

                    b.ToTable("NailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesign", b =>
                {
                    b.Property<int>("NailDesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailDesignId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MinPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("NailDesignId");

                    b.ToTable("NailDesigns");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesignImage", b =>
                {
                    b.Property<int>("NailDesignImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailDesignImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NailDesignId")
                        .HasColumnType("integer");

                    b.HasKey("NailDesignImageId");

                    b.HasIndex("NailDesignId");

                    b.ToTable("NailDesignImages");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailProcedure", b =>
                {
                    b.Property<Guid>("NailProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NailVariantId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.HasKey("NailProcedureId");

                    b.HasIndex("NailVariantId");

                    b.HasIndex("ProcedureId");

                    b.ToTable("NailProcedures");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailRequiredSkill", b =>
                {
                    b.Property<Guid>("NailRequiredSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("NailVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("SkillTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("NailRequiredSkillId");

                    b.HasIndex("SkillTypeId");

                    b.HasIndex("NailVariantId", "SkillTypeId")
                        .IsUnique();

                    b.ToTable("NailRequiredSkills");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailShape", b =>
                {
                    b.Property<int>("NailShapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailShapeId"));

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("NailShapeId");

                    b.ToTable("NailShapes");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailSurface", b =>
                {
                    b.Property<int>("NailSurfaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailSurfaceId"));

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ShaderParam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("NailSurfaceId");

                    b.ToTable("NailSurfaces");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailVariant", b =>
                {
                    b.Property<int>("NailVariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NailVariantId"));

                    b.Property<string>("ColorJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NailDesignId")
                        .HasColumnType("integer");

                    b.Property<int?>("NailShapeId")
                        .HasColumnType("integer");

                    b.Property<int?>("NailSurfaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("NailVariantId");

                    b.HasIndex("NailDesignId");

                    b.HasIndex("NailShapeId");

                    b.HasIndex("NailSurfaceId");

                    b.ToTable("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Procedure", b =>
                {
                    b.Property<Guid>("ProcedureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("ProcedureId");

                    b.ToTable("Procedures");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Salon", b =>
                {
                    b.Property<Guid>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("SalonId");

                    b.ToTable("Salons");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.SalonOperatingHour", b =>
                {
                    b.Property<Guid>("OperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("CloseTime")
                        .HasColumnType("interval");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("OpenTime")
                        .HasColumnType("interval");

                    b.Property<Guid>("SalonId")
                        .HasColumnType("uuid");

                    b.HasKey("OperatingHourId");

                    b.HasIndex("SalonId");

                    b.ToTable("SalonOperatingHours");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Schedule", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NailArtistId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("ShiftEnd")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("ShiftStart")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ScheduleId");

                    b.HasIndex("NailArtistId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Services", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.SkillType", b =>
                {
                    b.Property<Guid>("SkillTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("SkillTypeId");

                    b.ToTable("SkillTypes");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SalonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active");

                    b.HasKey("UserId");

                    b.HasIndex("SalonId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailArtist", "NailArtist")
                        .WithMany()
                        .HasForeignKey("NailArtistId");

                    b.HasOne("Nailify.Capstone.Domain.Entities.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("NailArtist");

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingHistory", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId");

                    b.HasOne("Nailify.Capstone.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingHistories")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingItem", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.CustomerNail", "CustomerNail")
                        .WithMany()
                        .HasForeignKey("CustomerNailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailVariant", "NailVariant")
                        .WithMany()
                        .HasForeignKey("NailVariantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.Services", "Service")
                        .WithMany("BookingItems")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("CustomerNail");

                    b.Navigation("NailVariant");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingProcedure", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.BookingItem", "BookingItem")
                        .WithMany("BookingProcedures")
                        .HasForeignKey("BookingItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailArtist", "CompletedBy")
                        .WithMany()
                        .HasForeignKey("CompletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookingItem");

                    b.Navigation("CompletedBy");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Category", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.CategoryType", "CategoryType")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.LoyaltyTier", "LoyaltyTier")
                        .WithMany("Customers")
                        .HasForeignKey("LoyaltyTierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("Nailify.Capstone.Domain.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyTier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerComponent", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerNail", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailArtist", "ApprovedArtist")
                        .WithMany()
                        .HasForeignKey("ApprovedArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailShape", "NailShape")
                        .WithMany()
                        .HasForeignKey("NailShapeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailSurface", "NailSurface")
                        .WithMany()
                        .HasForeignKey("NailSurfaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedArtist");

                    b.Navigation("NailShape");

                    b.Navigation("NailSurface");

                    b.Navigation("Salon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerNailComponent", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.CustomerComponent", "CustomerComponent")
                        .WithMany("CustomerNailComponents")
                        .HasForeignKey("CustomerComponentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.CustomerNail", "CustomerNail")
                        .WithMany("CustomerNailComponents")
                        .HasForeignKey("CustomerNailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("CustomerComponent");

                    b.Navigation("CustomerNail");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.FavoriteNail", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany()
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailVariant", "NailVariant")
                        .WithMany()
                        .HasForeignKey("NailVariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NailDesign");

                    b.Navigation("NailVariant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.LoyaltyTransaction", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.Customer", "Customer")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.LoyaltyTier", "LoyaltyTier")
                        .WithMany()
                        .HasForeignKey("LoyaltyTierIdAtTime")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("LoyaltyTier");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtist", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.User", "Account")
                        .WithOne()
                        .HasForeignKey("Nailify.Capstone.Domain.Entities.NailArtist", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtistSkill", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailArtist", "NailArtist")
                        .WithMany("NailArtistSkills")
                        .HasForeignKey("NailArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.SkillType", "SkillType")
                        .WithMany("NailArtistSkills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NailArtist");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailCategory", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Category", "Category")
                        .WithMany("NailCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany("NailCategories")
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("NailDesign");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailComponent", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Component", "Component")
                        .WithMany("NailComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailVariant", "NailVariant")
                        .WithMany("NailComponents")
                        .HasForeignKey("NailVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("NailVariant");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesignImage", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany("NailDesignImages")
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NailDesign");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailProcedure", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailVariant", "NailVariant")
                        .WithMany("NailProcedures")
                        .HasForeignKey("NailVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.Procedure", "Procedure")
                        .WithMany("NailProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NailVariant");

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailRequiredSkill", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailVariant", "NailVariant")
                        .WithMany("NailRequiredSkills")
                        .HasForeignKey("NailVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.SkillType", "SkillType")
                        .WithMany("NailRequiredSkills")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NailVariant");

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailVariant", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailDesign", "NailDesign")
                        .WithMany("NailVariants")
                        .HasForeignKey("NailDesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailShape", "NailShape")
                        .WithMany("NailVariants")
                        .HasForeignKey("NailShapeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nailify.Capstone.Domain.Entities.NailSurface", "NailSurface")
                        .WithMany("NailVariants")
                        .HasForeignKey("NailSurfaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("NailDesign");

                    b.Navigation("NailShape");

                    b.Navigation("NailSurface");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.SalonOperatingHour", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Salon", "Salon")
                        .WithMany("OperatingHours")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.NailArtist", "NailArtist")
                        .WithMany("Schedules")
                        .HasForeignKey("NailArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NailArtist");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.User", b =>
                {
                    b.HasOne("Nailify.Capstone.Domain.Entities.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingHistories");

                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.BookingItem", b =>
                {
                    b.Navigation("BookingProcedures");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Category", b =>
                {
                    b.Navigation("NailCategories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CategoryType", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Component", b =>
                {
                    b.Navigation("NailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Customer", b =>
                {
                    b.Navigation("LoyaltyTransactions");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerComponent", b =>
                {
                    b.Navigation("CustomerNailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.CustomerNail", b =>
                {
                    b.Navigation("CustomerNailComponents");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.LoyaltyTier", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailArtist", b =>
                {
                    b.Navigation("NailArtistSkills");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailDesign", b =>
                {
                    b.Navigation("NailCategories");

                    b.Navigation("NailDesignImages");

                    b.Navigation("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailShape", b =>
                {
                    b.Navigation("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailSurface", b =>
                {
                    b.Navigation("NailVariants");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.NailVariant", b =>
                {
                    b.Navigation("NailComponents");

                    b.Navigation("NailProcedures");

                    b.Navigation("NailRequiredSkills");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Procedure", b =>
                {
                    b.Navigation("NailProcedures");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Salon", b =>
                {
                    b.Navigation("OperatingHours");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.Services", b =>
                {
                    b.Navigation("BookingItems");
                });

            modelBuilder.Entity("Nailify.Capstone.Domain.Entities.SkillType", b =>
                {
                    b.Navigation("NailArtistSkills");

                    b.Navigation("NailRequiredSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
